api = "0.5"

[buildpack]
  id = "evankanderson/pyfun"
  name = "Evan's Function Buildpack"
  version = "0.1.0"

[metadata]
  include-files = ["buildpack.toml"]


## I would like to write the following, but it appears that you can't meta-meta-builpack...
# [[order]]

# [[order.group]]
# id = "packeto-community/python"
# version = "0.5.0"

# [[order.group]]
# id = "evankanderson/pyfun-addin"
# version = "0.0.1"

# Copied from https://github.com/paketo-community/python
[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.4.1"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-community/pipenv-install"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "evankanderson/pyfun-addin"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.4.1"

  [[order.group]]
    id = "paketo-community/pip-install"
    version = "0.1.2"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "evankanderson/pyfun-addin"
    version = "0.0.4"