# Build in this directory via:
#
# pack buildpack package ekanderson/pyfun-addin:0.1.0 --publish

api = "0.5"

[buildpack]
  id = "evankanderson/pyfun-addin"
  version = "0.1.0"
  name = "Evan's pyfun addin"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
